# Generated by Django 3.2.19 on 2023-07-14 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specimen',
            old_name='date_found',
            new_name='when_found',
        ),
        migrations.AddField(
            model_name='specimen',
            name='author',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='specimen_upload', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specimen',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('comment_content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='museum.specimen')),
            ],
        ),
    ]
