# Generated by Django 3.2.19 on 2023-07-14 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_auto_20230714_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('comment_content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='museum.specimen')),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
