# Generated by Django 3.2.19 on 2023-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_auto_20230714_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='species_name',
        ),
        migrations.AddField(
            model_name='specimen',
            name='english_name',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='specimen',
            name='latin_name',
            field=models.CharField(default='latin name', max_length=200),
        ),
    ]
