# Generated by Django 3.2.19 on 2023-07-26 08:50

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_specimen_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='museum.specimen'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='specimen_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
