# Generated by Django 3.2.19 on 2023-11-18 12:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_auto_20230726_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='specimen_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
