# Generated by Django 3.2.19 on 2023-11-18 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museum', '0007_alter_specimen_specimen_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='specimen',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddField(
            model_name='specimen',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='museumspecimen_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='museum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='english_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='latin_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='when_found',
            field=models.DateTimeField(),
        ),
    ]
