# Generated by Django 3.2.19 on 2023-11-18 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museum', '0008_auto_20231118_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimen_upload', to=settings.AUTH_USER_MODEL),
        ),
    ]
